name: foxplot
channels:
    - conda-forge
dependencies:
    - numpy
    - pip >= 21.3.1
    - pip:
        - foxplot
        - furo >= 2023.8.17
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
