name: foxplot
channels:
    - conda-forge
dependencies:
    - ipython
    - msgpack-python
    - numpy
    - pip
    - pip:
        - furo >= 2023.8.17
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
        - uplot-python
