name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    lint:
        name: "Code style"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Setup pixi"
              uses: prefix-dev/setup-pixi@v0.8.8
              with:
                  pixi-version: v0.44.0
                  cache: true

            - name: "Run linting"
              run: |
                  pixi run -e lint lint

    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Setup pixi"
              uses: prefix-dev/setup-pixi@v0.8.8
              with:
                  pixi-version: v0.44.0
                  cache: true

            - name: "Install coveralls"
              run: |
                  pip install coveralls

            - name: "Check code coverage"
              run: |
                  pixi run -e coverage coverage

            - name: "Coveralls"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  coveralls --service=github

    test:
        name: "Test ${{ matrix.os }} with Python ${{ matrix.python-version }}"
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Setup pixi"
              uses: prefix-dev/setup-pixi@v0.8.8
              with:
                  pixi-version: v0.44.0
                  cache: true

            - name: "Test with pixi"
              run: |
                  pixi run -e test-py${{ matrix.python-version | replace('.', '') }} test

    ci_success:
        name: "CI success"
        runs-on: ubuntu-latest
        needs: [coverage, lint, test]
        steps:
            - run: echo "CI workflow completed successfully"
